### ISSUE TITLE
Access to A11yDialogInstance type in a TypeScript project

### ISSUE THREAD

**Issue by findawayer** [KittyGiraudel/react-a11y-dialog#110]
```tsx
import { A11yDialog, A11yDialogProps } from 'react-a11y-dialog';

// hmm... 🤔 
type A11yDialogInstance = Parameters<NonNullable<A11yDialogProps['dialogRef']>>[0];

function SomeComponent() {
  const dialogRef = React.useRef<A11yDialogInstance>();
  const openDialog = dialogRef.current?.show();
  
  return (
    <>
      <button onClick={openDialog}>Open</button>
      {/* ... */}
      <A11yDialog dialogRef={dialog => (dialogRef.current = dialog)}>
        Lorem ipsum
      </A11yDialog>
    </>
  );
}
```

I would like to have my `dialogRef` type-safe, but the `A11yDialogInstance` type in the [package's type declaration file](https://github.com/KittyGiraudel/react-a11y-dialog/blob/4a86ea3196327c666f48123253f80ad29f11bb2d/index.d.ts#L2) is not accessible from outside. I tried to extract it like above, but still hoping for a non hard-coded solution. How can I achieve this?

**Comment by KittyGiraudel** [comment]
Hello there,

Allow me to ping @morkro on this as I have never worked with TypeScript. Hopefully he’ll be able to help in the upcoming week. :)

**Comment by developerfranky** [comment]
@findawayer  I do agree it'd be nice to access `A11yDialogInstance` directly from `react-a11y-dialog`. In the meantime, a workaround is to import it directly from `a11y-dialog` since `a11y-dialog` is a dependency. 

![image](https://user-images.githubusercontent.com/45829716/143059547-87e73c11-eaa1-44f1-b9cf-5ce4acdc609a.png)

**Comment by findawayer** [comment]
@developerfranky Good call! The suggested code looks better, I would steal it for future implementations.

**Comment by KittyGiraudel** [comment]
I’ll close this then. :)
