### ISSUE TITLE
Dialog Ref in Example

### ISSUE THREAD

**Issue by roblevintennis** [KittyGiraudel/react-a11y-dialog#129]
Hi Kitty

I did a little test to build a local version of the Readme's [Example](https://github.com/KittyGiraudel/react-a11y-dialog#example) and (for me) it seems like the dialog ref with same name is somehow shadowed and so throws an undefined error when I tried to run the app. It worked if I simply changed to:

```js
dialogRef={dialogInstance => (dialog.current = dialogInstance)}
```

I'd be happy to update the top-level readme if you'd like. It's pretty minor but might help folks new to react / javascript.

___

PS
Here's [my little test](https://github.com/KittyGiraudel/react-a11y-dialog/compare/main...roblevintennis:example-app-test?expand=1) in case it's helpful to see. I basically setup a Vite app, then built react-a11y-dialog and then use `npm pack` to generate a tarball and then install that locally. It's something I've come to favor for testing my own packages locally.

**Comment by roblevintennis** [comment]
Btw, if you do want me to make above update…

Another small UX thing for folks new to the library is how key the following piece of CSS is to visually "know" that the core library is working:

```css
.dialog[aria-hidden="true"] {
  display: none;
}
```

I know you painstakingly point this and many other things out in the docs proper. But I wonder if a small comment for folks either in the code example or GH readme just for folks trying to directly get the barebones or react version of a11y-dialog running would be helpful. If you do lmk your preference of how/where to put it and I can add it to PR.

**Comment by KittyGiraudel** [comment]
About your initial comment, you’re totally right. If you’d like to issue a PR with the following:

```diff
- dialogRef={dialog => (dialog.current = dialog)}
+ dialogRef={instance => (dialog.current = instance)}
```

I’ll happily merge it. :)

**Comment by KittyGiraudel** [comment]
About your second point, also very fair. Maybe the README could mention that some styles are needed, as recommended in the a11y-dialog docs, and link to it. Happy to review a PR as well. :)

**Comment by KittyGiraudel** [comment]
Done with #130.
