### ISSUE TITLE
React 18: ref type error

### ISSUE THREAD

**Issue by roelfjan** [KittyGiraudel/react-a11y-dialog#193]
It seems that the type of the `ref` property has changed in React 18. 

```
<div ref={attr.container.ref}
```

The above example now gives the error:
`Type '(node: ReactNode) => void' is not assignable to type 'LegacyRef<HTMLDivElement> | undefined'.`.

**Comment by thulstrup** [comment]
Changing `ref: (node: React.ReactNode) => void` to `ref: (node: HTMLDivElement) => void` in the `A11yDialogConfig` interface seems to do the trick.

**Comment by KittyGiraudel** [comment]
Any chance you'd feel like opening a PR?

**Comment by anastasiiayeromina** [comment]
Hi there! I've opened a PR since I required this fix as well.

**Comment by KittyGiraudel** [comment]
Addressed in 6.2.0. Thanks! ✨
