### ISSUE TITLE
`onHide` event

### ISSUE THREAD

**Issue by adamduncan** [KittyGiraudel/react-a11y-dialog#232]
We're looking to invoke some functionality related to the dialog contents (reset a form) when a user closes the dialog. I'm not sure how this would be achieved (looking at the current props API related to the close button) without having to go the [Hook approach](https://github.com/KittyGiraudel/react-a11y-dialog#hook) and putting the form together ourselves with our own `onClick` handler on the close button.

Is there an approach I'm missing here? Or would exposing some events (`onHide`) in the top-level API be something to explore, similar to the [JS version](https://a11y-dialog.netlify.app/advanced/events) of the plugin? (Something you touch on in #58)

---

To achieve this currently, one option is to manage an additional piece of state (timestamp) outside of the dialog and update that every time the dialog is opened. This way we can `useEffect` to track when it changes as an indication the modal's been closed and re-opened.

Another is to explore digging into the ~~`$el` itself and using native JS methods (`addEventListener('hide', ...`)~~ _Edit:_ `dialog.current?.on()` ref method, but feels a little clumsy in React land.

**Comment by KittyGiraudel** [comment]
Hey Adam,

You should have access to the dialog instance, so you can just bind listeners there.

```js

const App = props => {
  const dialog = React.useRef()

  useEffect(() => {
    const instance = dialog.current 

    if (instance) instance.on('hide', props.resetForm)
    
    return () => {
      if (instance) instance.off('hide', props.resetForm)
    }
  }, [props.resetForm])

  return (
    <div>
      <button type='button' onClick={() => dialog.current.show()}>
        Open the dialog
      </button>

      <A11yDialog
        id='my-accessible-dialog'
        dialogRef={instance => (dialog.current = instance)}
        title='The dialog title'
      >
        <p>Some content for the dialog.</p>
      </A11yDialog>
    </div>
  )
}
```

**Comment by adamduncan** [comment]
Ah, yep. Thanks @KittyGiraudel. Appreciate the suggestion 👍 

If you were considering expanding the API in future, perhaps callbacks for events could be a nice approach to abstract some of the effect setup away. Happy to close this one out. Thank you.

**Comment by KittyGiraudel** [comment]
I wanted to keep the wrapper as thin as possible over the core library but I might revisit that decision in a future version. In the meantime, you could write your own component around react-a11y-dialog to enhance the API to better suit your needs. :)
