### ISSUE TITLE
A11yDialogInstance types mismatch

### ISSUE THREAD

**Issue by jgarplind** [KittyGiraudel/react-a11y-dialog#275]
Hi there,

Thanks for sharing this library with the world :)

Using `react-a11y-dialog 6.2.0` with `a11y-dialog 8.0.1`, I have run into a typing problem.

Using React and Typescript, we have had to install `a11y-dialog` as well just to get access to the proper `A11yDialogInstance` type (specifically for usage in setting up a `dialogRef`: `const dialogRef = useRef<A11yDialogInstance>();`.

Now that `a11y-dialog` has been updated with a new interface (and this wrapper library has not), that approach leads to mismatches.

Having thought about it a bit, I have some suggestions (and a workaround) to share:

## Suggestions
1. Export the `A11yDialogInstance` type from _this_ library, to ensure that consumers of the library can use the same type as the library itself, not having to resort to other hacks/workarounds
2. Bump the dependency to `a11y-dialog` in `package.json` and release a new version of this library to keep in sync with `a11y-dialog`.

## Workaround
Similar to 1, the `A11yDialogInstance` type can be deduced from exported types, for example like so: `type A11yDialogInstance = ReturnType<typeof useA11yDialog>[0];`. However, this is obviously making ourselves reliant on a structure that is not meant to be used this way, and may not persist over package versions, so it would be great if the library explicitly exported `A11yDialogInstance` moving forward.

If you (partially or fully) share my sentiments, I would happily provide a PR.

Thanks,
Joel

**Comment by KittyGiraudel** [comment]
Dear Joel,

Thank you for opening an issue. In fact, you’re very right! We started updating react-a11y-dialog following the a11y-dialog v8 release but we never got to release it.

One thing I’m a little confused with is that the current version of react-a11y-dialog (6.2.0) uses a11y-dialog@^7.1.0, which means it should come with v7 types, not v8. So I’m not sure why we’re having an issue in the first place?

In any case, I should get on wrapping up react-a11y-dialog@7. :)

**Comment by KittyGiraudel** [comment]
Alright, react-a11y-dialog v7 is out. Could you try it out and let me know if that solves your problem?

**Comment by jgarplind** [comment]
> One thing I’m a little confused with is that the current version of react-a11y-dialog (6.2.0) uses a11y-dialog@^7.1.0, which means it should come with v7 types, not v8. So I’m not sure why we’re having an issue in the first place?

That is probably just an error on my side. We are using `pnpm` for package management, and by default it won't let you access dependencies that you didn't explicitly install. Since I wanted the types from `a11y-dialog`, rather than configuring `pnpm`, I just installed `a11y-dialog`. Upon updating `a11y-dialog` manually, I ran into this issue. Hope that clarifies things, and in particular that it is not the most normal case that most users will experience.

> Alright, react-a11y-dialog v7.0.2 is out. Could you try it out and let me know if that solves your problem?

It does! I would however personally prefer that `react-a11y-dialog` also (re-)exports the non-standard types that are required to make full use of it (which for `dialogRef` includes the default export from `a11y-dialog`), but that is of course up to you if you think that is a good solution for your library.

All things considered, things work just as well as before the v8 release, so I think you can close this issue whenever you see fit!

**Comment by KittyGiraudel** [comment]
@jgarplind If you want to issue a PR to make re-export the a11y-dialog types, I’ll review, merge and deploy it. :)

**Comment by KittyGiraudel** [comment]
Solved in https://github.com/KittyGiraudel/react-a11y-dialog/releases/tag/7.1.0. Thanks!
